config/routes.rb
Rails.application.routes.draw do

  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destory'
  get 'login_out' => 'sessions#destory'
 
  resources :numbers 
  resources :companies 

  resources :sessions 
  resources :customers do
    get   'bill', on: :member
    get   'export', on: :member
  end
  
  resources :company_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :number_import_logs do
    post   'upload', on: :collection
  end
  
  resources :issue_numbers

  resources :issue_number_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :bills 

  resources :bill_items

  resources :bill_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  root 'welcome#index'

end

app/models/company_import_log.rb
class CompanyImportLog < ImportLog
	has_many :companies

	def self.build(tmp_file)
		base_hash = save_upload_file(tmp_file)
    xlsx = Roo::Spreadsheet.open(base_hash[:file_path])
    log = CompanyImportLog.new do |l|
      l.file_name = base_hash[:file_name]
      l.file_path = base_hash[:file_path]
    end
    success_companies =[]
    errors = []
    xlsx.each_row_streaming(pad_cells: true, offset: 1) do |row|
      company = Company.new do |c|
        c.tel_office = row[0].cell_value.strip
        c.name = row[1].cell_value.strip
        c.bill_num = row[2].cell_value.strip
        c.apply_at = row[3].value if row[3]!=nil
      end
      company.valid?
      if company.errors.any?
        errors.push("第#{row[0].coordinate.row}行:#{company.errors.full_messages}.")
      else  
        success_companies.push(company)
      end
    end
    if success_companies.size > 0
      log.companies = success_companies 
    end
    log.remark = "导入数据成功#{success_companies.size}条"
    unless errors.empty? 	
    	ImportLog.delete_file_by log.file_path
    	raise errors.join(ImportLog::FILE_TAG) 
    end
    if success_companies.blank?
      ImportLog.delete_file_by log.file_path
      raise "无数据,请重新导入."
    end
    return log
	end
end

app/controllers/company_import_logs_controller.rb
class CompanyImportLogsController < ApplicationController
  before_action :set_companyImportLog, only: [:show, :edit, :update, :destroy]

  # GET /company_import_log
  # GET /company_import_log.json
  def index
  	 @company_import_log_grid = initialize_grid(CompanyImportLog, 
      order:'id', 
      order_direction: 'desc')
  end

  def show
    @companies_grid = initialize_grid(Company, 
        conditions: "company_import_log_id = #{@company_import_log.id}",
        order: 'id', 
        order_direction: 'desc')
  end

  def download
    send_file "#{Rails.root}/public/templet/company.xlsx",filename:"套餐导入模板.xlsx"
  end

  def upload
    # @company_import_log = companyImportLog_params()
    @company_import_log = CompanyImportLog.build(params[:file])
    @company_import_log.save!
    respond_to do |format|
      format.html { redirect_to @company_import_log, notice: '上传成功'}
    end
  rescue => e
    @errors =  e.message.split(ImportLog::FILE_TAG)
    respond_to do |format|
      format.html { render 'error'}
    end
  end

  def destroy
    @company_import_log.destroy
    respond_to do |format|
      format.html { redirect_to company_import_logs_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

	private
    def set_companyImportLog
      @company_import_log = CompanyImportLog.find(params[:id])
    end

end

app/helpers/company_import_logs_helper.rb
module CompanyImportLogsHelper
end

app/views/company_import_logs/destroy.html.erb
<h1>CompanyImportLog#destroy</h1>
<p>Find me in app/views/company_import_log/destroy.html.erb</p>

app/views/company_import_logs/error.html.erb
<div id="error_explanation">
  <h2>错误:</h2>
  <ul>
  <% @errors.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<%= link_to '返回', company_import_logs_path %>

app/views/company_import_logs/index.html.erb
<%= form_tag '/company_import_logs/upload', multipart: true,
 :class => "form-inline", :role => "form" do %>
  <%= file_field_tag  "file", style:"display:none", id:"lefile"%>
  <div class="form-group">
    <input id="photoCover" class="input-large" type="text" readonly="true">
    <button id="selectBtn" type="button" class="btn btn-default">
      选择文件
    </button>
  </div>
  <button id="uploadBtn" type="button" class="btn">
      上传
  </button>
  <%= submit_tag "上传" , class:"btn", id:"submit_btn", style:"display:none"%>
  <div class="form-group">
    <%= link_to "模板下载" ,download_company_import_logs_path %>
  </div>
<% end %>

<h3>导入记录</h3>
<%= grid(@company_import_log_grid ) do |g|

  g.column name:"上传文件名称", attribute: 'file_name' do |companyImportLog|
    companyImportLog.file_name
  end

  g.column name:"上传时间", attribute:'created_at'   do |companyImportLog|
    companyImportLog.created_at.strftime('%Y-%m-%d') 
  end

  g.column name:"说明", attribute:'remark', filter:false   do |companyImportLog|
    companyImportLog.remark
  end

  g.column do |companyImportLog|
    link_to('查看', companyImportLog )
  end
  
  g.column do |companyImportLog|
    link_to('删除', companyImportLog, method: :delete, 
      data: { confirm: "确定删除?" } )
  end
end -%>

<%= link_to '返回', companies_path %>

app/views/company_import_logs/show.html.erb
<p>
  <strong>文件名称</strong>
  <%= @company_import_log.file_name %>
</p>
<p>
  <strong>导入时间</strong>
  <%= @company_import_log.created_at.strftime("%Y-%m-%d") %>
</p>
<p>
  <strong>导入说明</strong>
  <%= @company_import_log.remark %>
</p>
<p>
  <strong>导入套餐列表</strong>
  <% if @companies_grid != nil %>
		<%= grid(@companies_grid) do |g|
		  g.column name:"#{company_attribute_name :name}", attribute: 'name' do |company|
		    company.name
		  end
		  g.column name:"#{company_attribute_name :bill_num}", attribute: 'bill_num'  do |company|
		    company.bill_num
		  end
		  g.column name:"#{company_attribute_name :tel_office}", attribute:'tel_office' do |company|
		    company.tel_office
		  end
		  g.column name:"#{company_attribute_name :apply_at}", attribute:'apply_at'   do |company|
		    company.apply_at
		  end
		end -%>
	<% end %>
</p>


<br>
<%= link_to '返回', company_import_logs_path %>