config/routes.rb
Rails.application.routes.draw do

  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destory'
  get 'login_out' => 'sessions#destory'
 
  resources :numbers 
  resources :companies 

  resources :sessions 
  resources :customers do
    get   'bill', on: :member
    get   'export', on: :member
  end
  
  resources :company_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :number_import_logs do
    post   'upload', on: :collection
  end
  
  resources :issue_numbers

  resources :issue_number_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :bills 

  resources :bill_items

  resources :bill_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  root 'welcome#index'

end

app/models/bill_import_log.rb
class BillImportLog < ImportLog
	has_one :bill, dependent: :destroy

	def self.build(tmp_file,year,month)
		base_hash = save_upload_file(tmp_file)
    log = self.new do |l|
      l.file_name = base_hash[:file_name]
      l.file_path = base_hash[:file_path]
    end
    bill = Bill.new do |b|
    	b.year = year
    	b.month = month
    end
    bill.valid?
    if bill.errors.any?
      raise bill.errors.full_messages.to_s
    end

    errors = []
    xlsx = Roo::Spreadsheet.open(base_hash[:file_path])
    xlsx.each_row_streaming(pad_cells: true, offset: 1) do |row|
      tel_office = row[0].cell_value.strip unless row[0].blank?
      company_name = row[1].cell_value.strip unless row[1].blank?
      phone_num = row[2].cell_value.strip unless row[2].blank?
      voice = row[3].cell_value.strip unless row[3].blank?
      message = row[4].cell_value.strip unless row[4].blank?
      internet = row[5].cell_value.strip unless row[5].blank?
      service = row[6].cell_value.strip unless row[6].blank?
      proxy = row[7].cell_value.strip unless row[7].blank?
    	if tel_office.blank? &&
        company_name.blank? &&
        phone_num.blank? &&
        voice.blank? &&
        message.blank? &&
        internet.blank? &&
        service.blank? &&
        proxy.blank?  
        next
      end
      row_count = row[0].coordinate.row unless row[0].blank?
      bill_item = BillItem.new do |bi|
        # company_id = Company.find_by name:company_name
				# bi.number = Number.joins(:company).find_by("phone_num=:phone_num and companies.name=:company_name",
    #                   {phone_num:phone_num,company_name:company_name})
        bi.number = Number.find_by(phone_num:phone_num)
        bi.voice = voice
        bi.message = message
        bi.internet = internet
        bi.service = service
        bi.proxy = proxy
      end
      # p bill_item.voice.class
      # p bill_item.inspect
      if  bill_item.valid?
        bill.bill_items << bill_item 
      else  
        errors.push("第#{row_count}行[号码(#{phone_num})]:#{bill_item.errors.full_messages}.")
      end
      
    end
    unless errors.empty? 	
    	ImportLog.delete_file_by log.file_path
    	raise errors.join(ImportLog::FILE_TAG) 
    end
    if bill.bill_items.blank?
      ImportLog.delete_file_by log.file_path
      raise "无数据,请重新导入."
    end
    log.bill = bill
    log.remark = "导入数据成功,#{year}年#{month}月的账单包含#{bill.bill_items.size}条明细记录"
    
    # raise "测试"
    return log
	end
end

app/controllers/bill_import_logs_controller.rb
class BillImportLogsController < ApplicationController
	before_action :set_billImportLog, only: [:show, :edit, :update, :destroy]

	def index
		@bill_import_log_grid = initialize_grid(BillImportLog, 
      order:'id', 
      order_direction: 'desc')
	end

  def download
    send_file "#{Rails.root}/public/templet/bill.xlsx",filename:"账单导入模板.xlsx"
  end

	def show
  end

  def upload
    @bill_import_log =BillImportLog.build(params[:file],params[:year],params[:month])
    @bill_import_log.save!
    respond_to do |format|
      format.html { redirect_to @bill_import_log, notice: '上传成功'}
    end
  rescue => e
    @errors =  e.message.split(ImportLog::FILE_TAG)
    respond_to do |format|
      format.html { render 'error'}
    end
  end

  def destroy
    @bill_import_log.destroy
    respond_to do |format|
      format.html { redirect_to bill_import_logs_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

	private
    def set_billImportLog
      @bill_import_log = BillImportLog.find(params[:id])
    end
end

app/helpers/bill_import_logs_helper.rb
module BillImportLogsHelper
end

app/views/bill_import_logs/error.html.erb
<div id="error_explanation">
  <h2>错误:</h2>
  <ul>
  <% @errors.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<%= link_to '返回', bill_import_logs_path %>

app/views/bill_import_logs/index.html.erb
<%= form_tag upload_bill_import_logs_path  , multipart: true,
 :class => "form-inline", :role => "form" do %>
  <%= file_field_tag  "file", style:"display:none", id:"lefile"%>
  <div class="form-group">
    <%= label_tag("账单月份") %>
    <%= select_tag :year,"<option>2016</option><option>2017</option>".html_safe, 
    include_blank: true %>
    <%= select_tag :month,"<option>1</option><option>2</option><option>3</option><option>4</option>
    <option>5</option><option>6</option><option>7</option><option>8</option><option>9</option>
    <option>10</option><option>11</option><option>12</option>".html_safe, 
    include_blank: true %>
  </div>
  <div class="form-group">
    <input id="photoCover" class="input-large" type="text" readonly="true">
    <button id="selectBtn" type="button" class="btn btn-default">
      选择文件
    </button>
  </div>
  <button id="uploadBtn" type="button" class="btn">
      上传
  </button>
  <%= submit_tag "上传" , class:"btn", id:"submit_btn", style:"display:none"%>
  <div class="form-group">
    <%= link_to "模板下载" ,download_bill_import_logs_path %>
  </div>
<% end %>

<h3>导入记录</h3>
<%= grid(@bill_import_log_grid ) do |g|

  g.column name:"上传文件名称", attribute: 'file_name' do |log|
    log.file_name
  end

  g.column name:"上传时间", attribute:'created_at'   do |log|
    log.created_at.strftime('%Y-%m-%d') 
  end

  g.column name:"说明", attribute:'remark', filter:false   do |log|
    log.remark
  end

  g.column do |log|
    link_to('查看', log )
  end
  
  g.column do |log|
    link_to('删除', log, method: :delete, 
      data: { confirm: "确定删除?" } )
  end
end -%>
<!-- 
<%= link_to '返回', bills_path %>
 -->

app/views/bill_import_logs/show.html.erb
<%- model_class = Bill -%>
<p>
  <strong>文件名称</strong>
  <%= @bill_import_log.file_name %>
</p>
<p>
  <strong>导入时间</strong>
  <%= @bill_import_log.created_at.strftime("%Y-%m-%d") %>
</p>
<p>
  <strong>导入说明</strong>
  <%= @bill_import_log.remark %>
</p>

<br>
<%= link_to '返回', bill_import_logs_path %>