config/routes.rb
Rails.application.routes.draw do

  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destory'
  get 'login_out' => 'sessions#destory'
 
  resources :numbers 
  resources :companies 

  resources :sessions 
  resources :customers do
    get   'bill', on: :member
    get   'export', on: :member
  end
  
  resources :company_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :number_import_logs do
    post   'upload', on: :collection
  end
  
  resources :issue_numbers

  resources :issue_number_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :bills 

  resources :bill_items

  resources :bill_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  root 'welcome#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates_presence_of :name, :tel_office
	validates_uniqueness_of :name
	has_many :numbers, -> {order("id DESC")}
	has_many :bills, -> {order("id DESC")}
	belongs_to :company_import_log
	belongs_to :issue_number_import_log
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies_grid = initialize_grid(Company, 
      order:'companies.id', 
      order_direction: 'desc',
      :custom_order => {
        'companies.name' => 'CONVERT( companies.name USING gbk ) COLLATE gbk_chinese_ci '
      })
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: '创建成功' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: '修改成功' }
        # format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        # format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    notice = '删除成功'
  rescue ActiveRecord::DeleteRestrictionError => e
    puts e.inspect
    notice = '删除失败:包含其他信息无法删除'
  rescue ActiveRecord::StatementInvalid => e
    puts e.inspect
    notice = '删除失败:包含其他信息无法删除'
  rescue Exception => e
    puts e.inspect
    notice = e.message
  ensure
    respond_to do |format|
      format.html { redirect_to companies_url, notice: notice }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :bill_num, :tel_office, :apply_at)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
	def company_model_name
		Company.model_name.human
	end
	def company_attribute_name(attribute)
		Company.human_attribute_name attribute
	end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>错误:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bill_num %><br>
    <%= f.text_field :bill_num %>
  </div>
  <div class="field">
    <%= f.label :tel_office %><br>
    <%= f.text_field :tel_office %>
  </div>
  <div class="field">
    <%= f.label :apply_at %><br>
    <%= f.date_select :apply_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>修改套餐</h1>

<%= render 'form' %>

<%= link_to '查看', @company %> |
<%= link_to '返回', companies_path %>

app/views/companies/index.html.erb
<h3><%= company_model_name %>列表</h3>
<%= grid(@companies_grid) do |g|

  g.column name:"#{company_attribute_name :name}", attribute: 'name' do |company|
    company.name
  end


  g.column name:"#{company_attribute_name :bill_num}", attribute: 'bill_num'  do |company|
    company.bill_num
  end

  g.column name:"#{company_attribute_name :tel_office}", attribute:'tel_office' do |company|
    company.tel_office
  end

  g.column name:"#{company_attribute_name :numbers_count}"  do |company|
    company.numbers.size
  end

  g.column name:"#{company_attribute_name :apply_at}", attribute:'apply_at'   do |company|
    company.apply_at
  end

  g.column do |company|
    link_to('查看', company )
  end
  g.column do |company|
    link_to('修改', edit_company_path(company) )
  end
  g.column do |company|
    link_to('删除', company, method: :delete, 
      data: { confirm: "#{('该套餐包含'+company.numbers.size.to_s+'号码,') unless company.numbers.size < 1 }确定删除?" } )
  end
end -%>
<br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_company_path,
            :class => 'btn btn-primary' %>
<%= link_to t('.import', :default => '导入'),
            company_import_logs_path,
            :class => 'btn btn-primary' %>

app/views/companies/new.html.erb
<h1>新建套餐</h1>

<%= render 'form' %>

<%= link_to '返回', companies_path %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => t_model_name(model_class) %></h1>
</div>
<p>
  <strong><%= t_attr_name(model_class, :name )%></strong>
  <%= @company.name %>
</p>

<p>
  <strong><%= t_attr_name(model_class, :bill_num )%></strong>
  <%= @company.bill_num %>
</p>

<p>
  <strong><%= t_attr_name(model_class, :tel_office )%></strong>
  <%= @company.tel_office %>
</p>

<p>
  <strong><%= t_attr_name(model_class, :apply_at) %></strong>
  <%= @company.apply_at %>
</p>
<p>
  <strong>号码列表</strong>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th><%= t_attr_name(Number,:phone_num)  %></th>
        <th><%= t_attr_name(Number,:real_num) %></th>
        <th><%= t_attr_name(Number,:apply_at)%></th>
      </tr>
    </thead>

    <tbody>
      <% @company.numbers.each do |number| %>
        <tr>
          <td><%= number.phone_num %></td>
          <td><%= number.real_num %></td>
          <td><%= number.apply_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>
<br>
<%= link_to '修改', edit_company_path(@company) %> |
<%= link_to '返回', companies_path %>