config/routes.rb
Rails.application.routes.draw do

  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destory'
  get 'login_out' => 'sessions#destory'
 
  resources :numbers 
  resources :companies 

  resources :sessions 
  resources :customers do
    get   'bill', on: :member
    get   'export', on: :member
  end
  
  resources :company_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :number_import_logs do
    post   'upload', on: :collection
  end
  
  resources :issue_numbers

  resources :issue_number_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  resources :bills 

  resources :bill_items

  resources :bill_import_logs do
    post   'upload', on: :collection
    get 'download', on: :collection
  end

  root 'welcome#index'

end

app/models/bill_item.rb
class BillItem < ActiveRecord::Base
	scope :active, ->(year,month) { joins(:bill).where("bills.year = ? and bills.month=?", year,month) }
	# validates_presence_of :voice, :message, :internet, :service, :proxy
	validates_presence_of :number,:message =>"不能为空或在套餐下未找到该号码"
	belongs_to :bill
	belongs_to :number
end

app/controllers/bill_items_controller.rb
class BillItemsController < ApplicationController
  before_action :set_bill_item, only: [:show, :edit, :update, :destroy]

  # GET /bill_items
  # GET /bill_items.json
  def index
    @bill_items = BillItem.all
  end

  # GET /bill_items/1
  # GET /bill_items/1.json
  def show
  end

  # GET /bill_items/new
  def new
    @bill_item = BillItem.new
  end

  # GET /bill_items/1/edit
  def edit
  end

  # POST /bill_items
  # POST /bill_items.json
  def create
    @bill_item = BillItem.new(bill_item_params)

    respond_to do |format|
      if @bill_item.save
        format.html { redirect_to @bill_item, notice: 'Bill item was successfully created.' }
        format.json { render :show, status: :created, location: @bill_item }
      else
        format.html { render :new }
        format.json { render json: @bill_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_items/1
  # PATCH/PUT /bill_items/1.json
  def update
    respond_to do |format|
      if @bill_item.update(bill_item_params)
        format.html { redirect_to @bill_item, notice: 'Bill item was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_item }
      else
        format.html { render :edit }
        format.json { render json: @bill_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_items/1
  # DELETE /bill_items/1.json
  def destroy
    @bill_item.destroy
    respond_to do |format|
      format.html { redirect_to bill_items_url, notice: 'Bill item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_item
      @bill_item = BillItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_item_params
      params.require(:bill_item).permit(:voice, :message, :internet, :service, :proxy, :bill)
    end
end

app/helpers/bill_items_helper.rb
module BillItemsHelper
end

app/views/bill_items/_form.html.erb
<%= form_for(@bill_item) do |f| %>
  <% if @bill_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_item.errors.count, "error") %> prohibited this bill_item from being saved:</h2>

      <ul>
      <% @bill_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voice %><br>
    <%= f.text_field :voice %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :internet %><br>
    <%= f.text_field :internet %>
  </div>
  <div class="field">
    <%= f.label :service %><br>
    <%= f.text_field :service %>
  </div>
  <div class="field">
    <%= f.label :proxy %><br>
    <%= f.text_field :proxy %>
  </div>
  <div class="field">
    <%= f.label :bill %><br>
    <%= f.number_field :bill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_items/edit.html.erb
<h1>Editing Bill Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_item %> |
<%= link_to 'Back', bill_items_path %>

app/views/bill_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bill Items</h1>

<table>
  <thead>
    <tr>
      <th>Voice</th>
      <th>Message</th>
      <th>Internet</th>
      <th>Service</th>
      <th>Proxy</th>
      <th>Bill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_items.each do |bill_item| %>
      <tr>
        <td><%= bill_item.voice %></td>
        <td><%= bill_item.message %></td>
        <td><%= bill_item.internet %></td>
        <td><%= bill_item.service %></td>
        <td><%= bill_item.proxy %></td>
        <td><%= bill_item.bill %></td>
        <td><%= link_to 'Show', bill_item %></td>
        <td><%= link_to 'Edit', edit_bill_item_path(bill_item) %></td>
        <td><%= link_to 'Destroy', bill_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill item', new_bill_item_path %>

app/views/bill_items/new.html.erb
<h1>New Bill Item</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_items_path %>

app/views/bill_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voice:</strong>
  <%= @bill_item.voice %>
</p>

<p>
  <strong>Message:</strong>
  <%= @bill_item.message %>
</p>

<p>
  <strong>Internet:</strong>
  <%= @bill_item.internet %>
</p>

<p>
  <strong>Service:</strong>
  <%= @bill_item.service %>
</p>

<p>
  <strong>Proxy:</strong>
  <%= @bill_item.proxy %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @bill_item.bill %>
</p>

<%= link_to 'Edit', edit_bill_item_path(@bill_item) %> |
<%= link_to 'Back', bill_items_path %>